# Generated by Django 4.2.4 on 2023-08-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_auto_20230803_2324"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ingridients",
            new_name="Ingredients",
        ),
        migrations.RenameModel(
            old_name="RecipesIngridients",
            new_name="RecipesIngredients",
        ),
        migrations.RenameField(
            model_name="ingredients",
            old_name="measure",
            new_name="measurement_unit",
        ),
        migrations.RemoveField(
            model_name="recipes",
            name="ingridients",
        ),
        migrations.AddField(
            model_name="recipes",
            name="Ingredients",
            field=models.ManyToManyField(
                through="recipes.RecipesIngredients", to="recipes.ingredients"
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="color",
            field=models.CharField(
                choices=[
                    ("#09DB4F", "Зеленый"),
                    ("#E26C2D", "Оранжевый"),
                    ("#B813D1", "Фиолетовый"),
                ],
                default="#09DB4F",
                max_length=7,
                verbose_name="Цвет в HEX",
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="tags",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="Уникальный слаг"
            ),
        ),
    ]
