# Generated by Django 4.2.4 on 2023-08-09 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_rename_ingridients_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredients",
            options={
                "ordering": ("id",),
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipes",
            options={
                "ordering": ("id",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipesingredients",
            options={
                "ordering": ("id",),
                "verbose_name": "Игредиенты рецепта",
                "verbose_name_plural": "Игредиенты рецептов",
            },
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={
                "ordering": ("id",),
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
            },
        ),
        migrations.RenameField(
            model_name="recipes",
            old_name="duration",
            new_name="cooking_time",
        ),
        migrations.RenameField(
            model_name="recipes",
            old_name="description",
            new_name="text",
        ),
    ]
