# Generated by Django 4.2.4 on 2023-08-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_remove_recipes_ingredients_alter_recipes_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipesingredients",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="recipes.recipes",
            ),
        ),
    ]
