# Generated by Django 4.2.4 on 2023-08-21 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0011_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="author",
            field=models.ForeignKey(
                help_text="Введите имя автора рецепта",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор рецепта",
            ),
        ),
    ]
