# Generated by Django 4.2.4 on 2023-09-05 16:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_alter_recipes_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredients",
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.AddField(
            model_name="recipes",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата публикации",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ingredients",
            name="measurement_unit",
            field=models.CharField(
                help_text="Введите единицу измерения",
                max_length=10,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                help_text="Укажите время приготовления рецепта в минутах",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Минимальное время приготовления"
                    )
                ],
                verbose_name="Время готовки",
            ),
        ),
        migrations.AlterField(
            model_name="recipesingredients",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Минимальное количество ингредиентов"
                    )
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="recipesingredients",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_ingredients"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_cart"
            ),
        ),
    ]
