# Generated by Django 4.2.4 on 2023-08-29 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_follow_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ("id",),
                "verbose_name": "Подписчик",
                "verbose_name_plural": "Подписчики",
            },
        ),
    ]
