# Generated by Django 4.2.4 on 2023-09-05 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_follow_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
